### ISSUE TITLE
Error "The file may be malicious, so the program is not going to read it."

### ISSUE THREAD

**Issue by lowl7** [OpenTalker/SadTalker#249]
I know I can write --disable-safe-unpickle in the webui_user.bat
But why do I need to do that? Why does it need me to compromise the security of it?

Wasn't this issue fixed already?

**Comment by vinthony** [comment]
It is already fixed. we find the unsafe pickle comes from the 3rd package of `face-alignment`:https://github.com/1adrianb/face-alignment, so we fix it with other alternatives.

**Comment by briwil** [comment]
I just loaded this extension for the first time and I also get this error... so its not fixed?

**Comment by vinthony** [comment]
> I just loaded this extension for the first time and I also get this error... so its not fixed?

are you using GPU?

**Comment by Jeffuy** [comment]
The same happened to me. It worked well a few days ago, but i'm receiving that msg now.

**Comment by briwil** [comment]
> > I just loaded this extension for the first time and I also get this error... so its not fixed?
> 
> are you using GPU?

Yes

**Comment by lowl7** [comment]
It seems to have been fixed as vinthony said, at least on my part it was my own mistake. When I downloaded the files through the Google Drive and places them in the checkpoints folder the error went away.
